<?php
/**
 * Plugin Name: Google Authenticator Wordpress
 * Plugin URI: https://cloudsofdream.com
 * Description: This plugin is use to add 2FA Google Authenticator into your Wordpress login and register forms.
 * Version: 1.0
 * Author: Sumit Sharma
 * Author URI: https://cloudsofdream.com
 **/

require_once 'googleLib/GoogleAuthenticator.php';

if($_POST['code'])
		{
				 $code=$_POST['code'];
				 $ga_code = $_POST['secret'];
				$secret=$ga_code;
				$ga = new GoogleAuthenticator();
				$checkResult = $ga->verifyCode($secret, $code, 2);    // 2 = 2*30sec clock tolerance
					print_r($checkResult);
					exit();
				if ($checkResult) 
				{
				$_SESSION['googleCode']=$code;

				} 
				else 
				{
				echo 'FAILED';
				
				}
				exit('fff');
		}


add_action( 'user_register', 'ga_registration_save', 10, 1 );

function ga_registration_save( $user_id ) {
		$ga = new GoogleAuthenticator();
		$secret = $ga->createSecret();
        update_user_meta($user_id, 'google_auth_code', $secret);

}

function add_my_stylesheet() 
{
    wp_enqueue_style( 'myCSS', plugins_url( '/css/style.css', __FILE__ ) );
}

add_action('admin_print_styles', 'add_my_stylesheet');


function customcode($user_login, $user) {
	$ga = new GoogleAuthenticator();
	$ga_code = get_user_meta($user->ID, 'google_auth_code', false);
	$ga_email = $user->user_email;
	$qrCodeUrl = $ga->getQRCodeGoogleUrl($ga_email, $ga_code,'Wordpress Sumit');

	
	
	?>
	<!DOCTYPE html>
		<html>
		<head>
		    <title>2-Step Verification using Google Authenticator</title>
		    <link rel="stylesheet" type="text/css" href="<?php echo plugins_url( '/css/style.css', __FILE__ ); ?>" charset="utf-8" />
		</head>
		<body>
			<div id="container">
				<h1>2-Step Verification using Google Authenticator</h1>
				<div id='device'>

		<p>Enter the verification code generated by Google Authenticator app on your phone.</p>
		<div id="img">
		<img src='<?php echo $qrCodeUrl; ?>' />
		</div>

		<form method="post" action="index.php">
		<label>Enter Google Authenticator Code</label>
		<input type="text" name="code" />
		<input type="hidden" name="secret" value="<?php echo $ga_code[0]; ?>" />
		<input type="submit" class="button"/>
		</form>
		</div>
		<div style="text-align:center">
			<h3>Get Google Authenticator on your phone</h3>
		<a href="https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8" target="_blank">
			<img class='app' src="<?php echo plugins_url( '/images/iphone.png', __FILE__ ); ?>" /></a>

		<a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en" target="_blank">
			<img class="app" src="<?php echo plugins_url( '/images/android.png', __FILE__ ); ?>" /></a>
		</div>
		</div>
		</body>
		</html>
	<?php 
	/*echo $user_login;
	print_r($ga_code);
  print_r($user->user_email);*/
  exit();
}
add_action('wp_login', 'customcode', 30, 2);

?>